### ISSUE TITLE
1. Объединение, пересечение, разность, симметрическая разность

### ISSUE THREAD

**Issue by TwoXowT** [Suvorovm/perl-labs#2]
Для двух произвольных массивов вычислить:
— объединение;
— пересечение;
—разность;	
—симметричную разность их элементов.

**Comment by Suvorovm** [comment]
минус объединение

**Comment by TwoXowT** [comment]
когда вводишь 0 при объявлении массива, он считает его как за '', БАГ

**Comment by Suvorovm** [comment]
Поправил это . Происходило из-за того, что нет строгой типизации

**Comment by TwoXowT** [comment]
Кстати ты в массив закидываешь числа типа 4\n 5\n 6\n они поэтому в столбик выстраиваются
юзай chomp(value)

**Comment by Suvorovm** [comment]
chomp не работает нормально 
Если че, попробуем в след лабе
